name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  run-hello-script:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Run hello script
        run: |
          ls - la
          ./hello.sh
